version: '3.8'
services:
  nginx:
    restart: always
    ports:
      - "82:82"
      - "81:81"
    depends_on:
      - pocketbase_db
    image:  ghcr.io/immo-be/proj-maplibre-polygon-proxy:new


  app:
    ports:
      - "3000:3000"
    image: ghcr.io/immo-be/proj-maplibre-polygon-app


  pocketbase_db:
    depends_on:
    - app

    ports:
      - '8090:8090'
    volumes:
      - pb_data:/usr/local/bin/pb_data
    image:  ghcr.io/immo-be/proj-maplibre-polygon-pocketbase_db


volumes:
  pb_data:
