version: '3.8'
services:
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
      - "82:82"
      - "80:80"
    depends_on:
      - pocketbase_db
    image:  ghcr.io/immo-be/proj-maplibre-polygon-proxy:new


  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    image: ghcr.io/immo-be/proj-maplibre-polygon-app


  pocketbase_db:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        TARGETOS: linux
        TARGETARCH: amd64
        VERSION: 0.2.8
    depends_on:
    - app

    ports:
      - '8090:8090'
    # command: ["serve", "--http=0.0.0.0:8090"]
    # stdin_open: true
    # tty: true
    volumes:
      - pb_data:/usr/local/bin/pb_data
    image:  ghcr.io/immo-be/proj-maplibre-polygon-pocketbase_db


volumes:
  pb_data:

  # db:
  #       image: postgres:13
  #       restart: always
  #       environment:
  #         POSTGRES_PASSWORD: password
  # db:
  #   image: postgres:16.2
  #   container_name: postgressql_db
  #   environment:
  #     POSTGRES_USER: baeldung
  #     POSTGRES_PASSWORD: baeldung
  #   ports:
  #     - "5432:5432"
  #   # volumes:
  #   #   - /data:/var/lib/postgresql/data
  #   restart: always
