version: '3.8'
services:
  # proxy:
  #   image: nginx:alpine
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./client
    volumes:
      - ./client:/client/
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - pocketbase_db
    stdin_open: true
    tty: true

  pocketbase_db:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        TARGETOS: linux
        TARGETARCH: amd64
        VERSION: 0.2.8
    ports:
      - '8090:8090'
    # command: ["serve", "--http=0.0.0.0:8090"]
    stdin_open: true
    tty: true
    volumes:
      - ./database:/pb/pb_data

  # db:
  #       image: postgres:13
  #       restart: always
  #       environment:
  #         POSTGRES_PASSWORD: password
  # db:
  #   image: postgres:16.2
  #   container_name: postgressql_db
  #   environment:
  #     POSTGRES_USER: baeldung
  #     POSTGRES_PASSWORD: baeldung
  #   ports:
  #     - "5432:5432"
  #   # volumes:
  #   #   - /data:/var/lib/postgresql/data
  #   restart: always
