# build stage
FROM --platform=linux/amd64 node:lts-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4173
RUN npm run build
# assumes the default SvelteKit host and port
ENV ORIGIN=http://hafen-planungstool.seefalke.info


CMD ["node", "build"]
